apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/*
        apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  steps:
    - name: run-nose-tests
      image: python:3.8
      script: |
        #!/bin/bash
        pip install nose
        nosetests /workspace/tests
